name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/authorized_keys
          ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIRECTORY }}
